# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-BitTorrent-LibBTT
version:      0.010
version_from: lib/Net/BitTorrent/LibBTT.pm
installdirs:  site
requires:
    APR:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
